name: nox-plugin-api-abuse
version: 0.1.0
track: dynamic-runtime
description: Detect API authorization flaws, BOLA vulnerabilities, and abuse patterns in server code
tools:
  - name: scan
    description: Scan source files for missing auth checks, BOLA risks, mass assignment, and verbose errors
